/**
 * Pointization constants for scenario demand generation.
 */

export const RESIDENTIAL_GRID_SUBDIVISION_PER_AXIS = 4;
export const RESIDENTIAL_GRID_CELL_SIZE_METERS = 1000;
export const RESIDENTIAL_GRID_SUBNODE_JITTER_METERS_OR_ZERO = 0;
export const WORKPLACE_POLYGON_POINTIZATION_MIN_AREA_SQUARE_METERS = 160000;
export const WORKPLACE_POLYGON_POINTIZATION_TARGET_SPACING_METERS = 250;
export const WORKPLACE_POLYGON_POINTIZATION_MAX_POINTS_PER_FEATURE = 16;
export const WORKPLACE_RUNTIME_MAX_DESTINATION_NODES = 1000;
